name: stripes_backend_helper
description: Stripes basic dataflow.
version: 0.0.1
homepage: https://github.com/dylanb7/stripes_backend_helper
publish_to: none

environment:
  sdk: ">=2.18.0-271.4.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
